package com.print.service;

import java.util.*;

public class Language extends java.util.ListResourceBundle {
  private static final Object[][] contents = new String[][]{
	{ "String_6", "没有指定合适的QueryStubObject对象！" },
	{ "String_16", "承前页…" },
	{ "String_17", "过次页…" },
	{ "String_27", "日" },
	{ "String_26", "月" },
	{ "String_25", "年" },
	{ "String_44", "行数据" },
	{ "String_43", "页的第" },
	{ "String_42", "绘制第" },
	{ "String_53", "页的标题" },
	{ "String_52", "绘制第" },
	{ "String_55", "页的表头" },
	{ "String_54", "绘制第" },
	{ "String_57", "页的表体" },
	{ "String_56", "绘制第" },
	{ "String_59", "页的表尾" },
	{ "String_58", "绘制第" },
	{ "String_61", "页的行高" },
	{ "String_60", "设置第" },
	{ "String_63", "页的分页符" },
	{ "String_62", "设置第" },
	{ "String_67", "页" },
	{ "String_66", "  第" },
	{ "String_65", "  打印日期：" },
	{ "String_64", "单位：" },
	{ "String_191", " 编制单位：" },
	{ "String_193", "打印日期：" },
	{ "String_194", "  第" },
	{ "String_196", "页" },
        { "String_197", " 共" },
	{ "String_249", "承前页…" },
	{ "String_250", "承后页…" },
	{ "String_262", "日" },
	{ "String_261", "月" },
	{ "String_260", "年" },
	{ "String_264", "打印设置" },
	{ "String_266", "打印机" },
	{ "String_267", "范围" },
	{ "String_268", "打印" },
	{ "String_269", "设置" },
	{ "String_270", "打印" },
	{ "String_271", "纸张" },
	{ "String_272", "名称:" },
	{ "String_273", "属性(R)" },
	{ "String_274", "状态:" },
	{ "String_275", "类型:" },
	{ "String_276", "位置:" },
	{ "String_278", "全部(A)" },
	{ "String_279", "页(G)" },
	{ "String_280", "从(F)" },
	{ "String_281", "到(T)" },
	{ "String_282", "整个工作薄(E)" },
	{ "String_283", "设置区域(N)" },
	{ "String_284", "%正常尺寸" },
	{ "String_285", "缩放:" },
	{ "String_286", "调整:" },
	{ "String_287", "页宽" },
	{ "String_288", "页高" },
	{ "String_291", "缺省纸张设置" },
	{ "String_293", "份数:" },
	{ "String_294", "纸张:" },
	{ "String_299", "确定" },
	{ "String_300", "取消" },
	{ "String_301", "缺省缩放设置" },
	{ "String_302", "纵向" },
	{ "String_303", "横向" },
	{ "String_304", "单色打印(C)" },
	{ "String_305", "打印" },
	{ "String_375", "承前页…" },
	{ "String_376", "过次页…" },
	{ "String_377", "PrintKey分割，可通过printObject定制" }};
  public Object[][] getContents() {
    return contents;
  }
}
